### PR TITLE
Version - 2.0

### PR DESCRIPTION
**Pull request by ysfchn**
### Features
* **Added ability to write full class name!**
   You can now write the full class name of components, and with this feature, it allows you to create extensions in Schema templates!
    class_text

* **Generate Schemas Instantly from AIA file!**
    You can use the brand-new Python tool called TemplateCreator to automatically generate templates! <br>[**⚡ Go to the TemplateCreator**](https://github.com/ysfchn/DynamicComponents-AI2/wiki/Creating-Templates)

### Blocks
* **RandomUUID**
   Makes a random unique UUID. Use this block in Create block if the component ID is not required for you.
   method_randomuuid

* **IsDynamic**
    Returns 'true' if component has created by Dynamic Components extension. Otherwise, 'false'.
   method_isdynamic

* **Move**
  Moves the component to another arrangement.
  method_move

* **SetOrder**
   Sets the position of the component according to its parent arrangement. Index starts from 1. Typing 0 (zero) will move the component to the end.
   method_setorder

* **GetOrder**
   Gets the position of the component according to its parent arrangement. Index starts from 1.
   method_getorder

* **SetProperties**  
   Allows to set multiple properties with dictionary. #25 by @StormiFire
   component_method (4)

* **VersionName**
   Returns the version name of the extension.
   setget_versionname

* **Invoke**
   Calls a method of any component. If the return value is not important for you, use with <code>evaluate but ignore result</code> block.
    method_invoke

* **ListDetails**
   Gives the information of the specified component with all properties, events, methods as JSON text.
   method_listdetails

## 🔄 Improved

* **Spaces will be deleted by default in property, class and component names.**
   If you add spaces in the property, class, and component names, they will be deleted by default to decrease the confusion.

* **SchemaCreated event now has two parameters, name and parameters.**
   event_schemacreated

## ⚠ Breaking Changes

* SchemaCreated event's parameter has changed so you will need to update your old blocks with new one manually.

* `GetDesignerProperties` has deleted. However, you can continue using the `ListDetails` block that gives more information about the component instead of just properties.
method_getdesignerproperties

### CODE REVIEW

**Comment by alanscot** [comment]
Thanks for GREAT enhancements but https://github.com/ysfchn/DynamicComponents-AI2/tree/main/TemplateCreator is not found 
    On Sunday, August 2, 2020, 10:26:08 AM PDT, Yusuf Cihan <notifications@github.com> wrote:  
 
 
Version 1.4

 ⭐ New

Features
   
   -    
Added ability to write full class name!   
You can now write the full class name of components, and with this feature, it allows you to create extensions in Schema templates!   


   -    
Generate Schemas from AIA file!   
You can use the brand-new Python tool called TemplateCreator to automatically generate templates!    
Go to the TemplateCreator


Blocks
   
   - RandomUUID   
Makes a random unique UUID. Use this block in Create block if component ID is not required for you.   


You can view, comment on, or merge this pull request online at:

  https://github.com/ysfchn/DynamicComponents-AI2/pull/18

Commit Summary
   
   - Added ability to write the full class name
   - Fix: Add titles to the exceptions
   - Bump version to 5
   - Update extension description
   - Add RandomUUID block
   - Documentation update
   - Update README.md
   - Remove Parameters on README.md
   - Update README.md
   - Update README.md
   - Update README.md
   - Clean-up
   - Added GitHub Actions
   - Code style
   - Update build.yml
   - Update build.yml
   - Update build.yml
   - ⚡ Template Creator

File Changes
   
   -  A .github/workflows/build.yml (19) 
   -  M .gitignore (173) 
   -  M README.md (291) 
   -  A TemplateCreator/LICENSE (21) 
   -  A TemplateCreator/README.md (30) 
   -  A TemplateCreator/TemplateCreate.py (76) 
   -  A TemplateCreator/cli.py (39) 
   -  A TemplateCreator/requirements.txt (2) 
   -  A assets/blocks/class_text.png (0) 
   -  A assets/blocks/component_block.png (0) 
   -  A assets/blocks/event_schemacreated.png (0) 
   -  A assets/blocks/method_changeid.png (0) 
   -  A assets/blocks/method_create.png (0) 
   -  A assets/blocks/method_getcomponent.png (0) 
   -  A assets/blocks/method_getdesignerproperties.png (0) 
   -  A assets/blocks/method_getid.png (0) 
   -  A assets/blocks/method_getname.png (0) 
   -  A assets/blocks/method_getproperty.png (0) 
   -  A assets/blocks/method_lastusedid.png (0) 
   -  A assets/blocks/method_randomuuid.png (0) 
   -  A assets/blocks/method_remove.png (0) 
   -  A assets/blocks/method_schema.png (0) 
   -  A assets/blocks/method_setproperty.png (0) 
   -  A assets/blocks/method_usedids.png (0) 
   -  A assets/blocks/setget_version.png (0) 
   -  A assets/blocks/text.png (0) 
   -  D blocks.png (0) 
   -  M src/com/yusufcihan/DynamicComponents/DynamicComponents.java (143) 

Patch Links:
   
   - https://github.com/ysfchn/DynamicComponents-AI2/pull/18.patch
   - https://github.com/ysfchn/DynamicComponents-AI2/pull/18.diff

**Comment by ysfchn** [comment]
@alanscot that's because TemplateCreator is not in the `main` branch yet. You can access the TemplateCreator from [here](https://github.com/ysfchn/DynamicComponents-AI2/tree/main/TemplateCreator).

**Comment by alanscot** [comment]
"here"  goes to https://github.com/ysfchn/DynamicComponents-AI2/tree/main/TemplateCreator( not found)
    On Sunday, August 2, 2020, 12:48:27 PM PDT, Yusuf Cihan <notifications@github.com> wrote:  
 
 


@alanscot that's because TemplateCreator is not in the main branch yet. You can access the TemplateCreator from here.

**Comment by ysfchn** [comment]
@alanscot Sorry, I just posted the wrong link 😅 Here is the right one: 
https://github.com/ysfchn/DynamicComponents-AI2/tree/beta/TemplateCreator

If you still can't access, just go to the `beta` branch and find the `TemplateCreator` folder.

**Pull request merged**
