### PR TITLE
Fix Invoke block issue

### LINKED ISSUE #27: Schema doesn't works for non-string values on 2.0

### PR DESCRIPTION
**Pull request by ysfchn**
Closes #27 

This PR will stay in Draft until all types of values are confirmed to work in the `Invoke` block.

### CODE REVIEW

**Comment by StormiFire** [comment]
Bump to **2.1.1** because of a bug fix.

**Comment by ysfchn** [comment]
You have bumped the version with your PR already, and 2.1.0 is not even released yet.

**Comment by StormiFire** [comment]
> You have bumped the version with your PR already, and 2.1.0 is not even released yet.

Bumping it to **2.1.1** would indicate a bug fix for **2.0** (already released like 3 days ago). When I bumped it to **2.1.0**, that was because I added a new feature (block).

**Comment by ysfchn** [comment]
> When I bumped it to 2.1.0, that was because I added a new feature (block).

But the thing is, 2.1.0 isn't released yet so it is an addition to version 2.1.0 which is still working on.

**Pull request merged**
